name: first

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: env | sort
  job2:
    needs: job1
    name: Second Jobs
    runs-on: windows-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: "Get-ChildItem Env: | Sort-Object Name"
  job3:
    name: Third Jobs
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: ls -l
  job4:
    needs: [job1,job2,job3]
    name: Forth Jobs
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        run: |
         pwd
         who
  job5:
    name: python-lint-check
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - name: Step two
        uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
      - name: Step three
        run: |
            echo ${{ env.DEV_NAME }}
            echo ${{ secrets.DEV_NAME }}